# Generated by Django 5.2.7 on 2025-12-17 02:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_customer_id', models.CharField(max_length=255, unique=True, verbose_name='Stripe顧客ID')),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='StripeサブスクリプションID')),
                ('status', models.CharField(choices=[('active', 'アクティブ'), ('canceled', 'キャンセル済み'), ('past_due', '支払い遅延'), ('incomplete', '未完了'), ('trialing', 'トライアル中')], default='incomplete', max_length=20, verbose_name='ステータス')),
                ('price', models.DecimalField(decimal_places=2, default=500.0, max_digits=10, verbose_name='月額料金')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='開始日')),
                ('next_billing_date', models.DateTimeField(blank=True, null=True, verbose_name='次回請求日')),
                ('canceled_at', models.DateTimeField(blank=True, null=True, verbose_name='キャンセル日')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': 'サブスクリプション',
                'verbose_name_plural': 'サブスクリプション',
                'ordering': ['-created_at'],
            },
        ),
    ]
