# Generated by Django 5.2.7 on 2025-12-17 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='price',
            field=models.DecimalField(decimal_places=2, default=300.0, max_digits=10, verbose_name='月額料金'),
        ),
    ]
