# Generated by Django 5.2.7 on 2025-12-21 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='prefecture',
            field=models.CharField(default='愛知県', max_length=10, verbose_name='都道府県'),
        ),
    ]
