# Generated by Django 5.2.7 on 2025-12-21 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_restaurant_prefecture'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='city',
            field=models.CharField(default='名古屋市', max_length=50, verbose_name='市区町村'),
        ),
    ]
