# Generated by Django 5.2.7 on 2025-12-24 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_restaurant_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.PositiveIntegerField(help_text='この席の定員数（2名、4名、8名など）', verbose_name='定員数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='restaurants.restaurant', verbose_name='店舗')),
            ],
            options={
                'verbose_name': 'テーブル',
                'verbose_name_plural': 'テーブル',
                'ordering': ['restaurant', 'capacity'],
                'indexes': [models.Index(fields=['restaurant', 'capacity'], name='restaurants_restaur_94469c_idx')],
            },
        ),
    ]
