# Generated by Django 5.2.7 on 2025-12-05 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0006_category_company'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
        migrations.RemoveField(
            model_name='category',
            name='sort_order',
        ),
    ]
