# Generated by Django 5.2.7 on 2025-12-06 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_is_owner_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='name_kana',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='tel',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='user',
            name='zipcode',
            field=models.CharField(max_length=8),
        ),
    ]
