# Generated by Django 5.2.7 on 2025-12-24 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
        ('restaurants', '0004_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='table',
            field=models.ForeignKey(blank=True, help_text='割り当てられた座席', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='restaurants.table', verbose_name='テーブル'),
        ),
    ]
